# spring.application.name=jobportal
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.security.user.name=admin
spring.security.user.password=admin123